In [38]:
#numpy is used for the matrix calculations and the concept of array
import numpy as np
j=[4,6,2,8,9]
j

[4, 6, 2, 8, 9]

In [ ]:
1) numpy                      array operations
2) pandas                     data manipulation and analysis
3) matplotlib and seaborn     graphical analysis
4) sklearn                    machine learning algorithms and techniques
5) statsmodels                statistical analysis
6) scipy                      statistical analysis

In [134]:
j=[2,5,4,2,1,3]
j

[2, 5, 4, 2, 1, 3]

In [136]:
d=np.array(j)
d

array([2, 5, 4, 2, 1, 3])

In [10]:
tuple(j)

(2, 5, 4, 2, 1, 3, 7)

In [24]:
type(d)

numpy.ndarray

In [26]:
d

array([2, 5, 4, 2, 1, 3, 7])

In [28]:
d.shape

(7,)

In [30]:
#list doesn't have any shape
j.shape

AttributeError: 'list' object has no attribute 'shape'

In [32]:
d.ndim

1

In [88]:
d.reshape

<function ndarray.reshape>

In [36]:
d.size

7

In [66]:
s=[[4,6,8,9,2],[5,3,5,7,5],[34,67,98,94,78],[23,4,5,67,78],[98,45,32,34,54]]
s

[[4, 6, 8, 9, 2],
 [5, 3, 5, 7, 5],
 [34, 67, 98, 94, 78],
 [23, 4, 5, 67, 78],
 [98, 45, 32, 34, 54]]

In [68]:
arr1=np.array(s)
arr1

array([[ 4,  6,  8,  9,  2],
       [ 5,  3,  5,  7,  5],
       [34, 67, 98, 94, 78],
       [23,  4,  5, 67, 78],
       [98, 45, 32, 34, 54]])

In [70]:
type(s)

list

In [72]:
type(arr1)

numpy.ndarray

In [74]:
arr1.shape

(5, 5)

In [76]:
arr1.size

25

In [78]:
arr1.ndim

2

In [167]:
arr1.reshape

<function ndarray.reshape>

In [138]:
h=d.reshape(2,3)
h

array([[2, 5, 4],
       [2, 1, 3]])

In [142]:
h.size

6

In [144]:
h.shape

(2, 3)

In [146]:
h.ndim

2

In [148]:
w=h.reshape(3,2)
w

array([[2, 5],
       [4, 2],
       [1, 3]])

In [150]:
w.shape


(3, 2)

In [152]:
w.size

6

In [154]:
w.ndim

2

In [169]:
m=[4,6,7,8,9,1,2,3,11,12]
m

[4, 6, 7, 8, 9, 1, 2, 3, 11, 12]

In [173]:
range(3,13,)

range(3, 13)

In [175]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [177]:
list(range(3,13,3))

[3, 6, 9, 12]

In [179]:
range(5,500,)

range(5, 500)

In [185]:
list(range(5,500,100))

[5, 105, 205, 305, 405]

In [197]:
tuple(range(5,520,110))

(5, 115, 225, 335, 445)

In [199]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [201]:
range(-1,-10)

range(-1, -10)

In [209]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [211]:
list(range(-1,-10,-2))

[-1, -3, -5, -7, -9]

In [213]:
list(range(-1,-10,-5))

[-1, -6]

In [215]:
list(range(10,-10,-1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, -1, -2, -3, -4, -5, -6, -7, -8, -9]

In [217]:
list(range(10,-10,-3))

[10, 7, 4, 1, -2, -5, -8]

In [219]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [229]:
list(range(-1,-10,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9]

In [231]:
[2.5,3,3.5,4,4.5]

[2.5, 3, 3.5, 4, 4.5]

In [233]:
range(2.5,5,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [235]:
#we can provide integer values and float values
np.arange(2.5,5,0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [239]:
2.5,5,0.5

(2.5, 5, 0.5)

In [243]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [247]:
for i in range(5,50,5):
    print("data",i)

data 5
data 10
data 15
data 20
data 25
data 30
data 35
data 40
data 45


In [249]:
j=[5,87,98,45,56,98,43,32,12,23]
j

[5, 87, 98, 45, 56, 98, 43, 32, 12, 23]

In [253]:
list(range(5,23))

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

In [255]:
j=[5,87,98,45,56,98,43,32,12,23]
j

[5, 87, 98, 45, 56, 98, 43, 32, 12, 23]

In [280]:
y=[]
x=[]
for i in range(len(j)):
    if i % 2 == 0:
        x.append(j[i])
    else:
        y.append(j[i])



In [282]:
x

[5, 98, 56, 43, 12]

In [284]:
y

[87, 45, 98, 32, 23]

In [9]:
import numpy as np

In [19]:
l=np.array([12,34,68,56,78])
l

array([12, 34, 68, 56, 78])

In [21]:
np.mean(l)

49.6

In [23]:
np.median(l)

56.0

In [25]:
np.var(l)

568.6400000000001

In [27]:
np.std(l)

23.84617369726221

In [29]:
np.max(l)

78

In [32]:
np.min(l)

12

In [40]:
#quantile means the 25% of given data
q1=np.quantile(l,0.25)
q1

34.0

In [42]:
q2=np.quantile(l,0.5)
q2

56.0

In [44]:
q3=np.quantile(l,0.75)
q3

68.0

In [46]:
np.random.rand(12,6)

array([[0.21519814, 0.05748081, 0.49363787, 0.69364294, 0.34168861,
        0.89171513],
       [0.83073433, 0.54402626, 0.76614724, 0.08251826, 0.83637868,
        0.67596805],
       [0.97254454, 0.04370161, 0.27965831, 0.88568148, 0.51676361,
        0.78161422],
       [0.74662795, 0.15187021, 0.29633814, 0.17671712, 0.39260476,
        0.2623356 ],
       [0.92553738, 0.31296059, 0.02146689, 0.35669392, 0.30224326,
        0.04744359],
       [0.2167832 , 0.10351135, 0.27726478, 0.33529527, 0.04603668,
        0.79197235],
       [0.2900498 , 0.32231508, 0.73625106, 0.67917821, 0.01737287,
        0.29626009],
       [0.29625907, 0.77237452, 0.36277028, 0.9031247 , 0.37956826,
        0.82348397],
       [0.76428141, 0.86189558, 0.62892755, 0.00333057, 0.2489485 ,
        0.5210316 ],
       [0.63350707, 0.38924216, 0.81816921, 0.73142076, 0.48222266,
        0.2713521 ],
       [0.91599343, 0.9233154 , 0.43275487, 0.24530809, 0.20594858,
        0.96342534],
       [0.4206768 , 0

In [48]:
np.random.rand()

0.6068854299463831

In [50]:
np.random.rand(1)

array([0.1815528])

In [70]:
r=np.random.rand(5,3,2)#0 to 1 range(mean,s.d,shape of array)
r

array([[[0.51131664, 0.07108906],
        [0.30894862, 0.5550283 ],
        [0.51152413, 0.75751614]],

       [[0.0888592 , 0.19684828],
        [0.89489894, 0.29362125],
        [0.27683132, 0.33449215]],

       [[0.93585328, 0.23793766],
        [0.65708242, 0.31892047],
        [0.79376398, 0.02591525]],

       [[0.18121148, 0.81491521],
        [0.84135904, 0.54972646],
        [0.89083941, 0.51795556]],

       [[0.19850581, 0.76616997],
        [0.4400053 , 0.29631037],
        [0.14961566, 0.13000564]]])

In [72]:
r.shape

(5, 3, 2)

In [74]:
r.size

30

In [76]:
r.ndim

3

In [84]:
np.random.randn(90,)

array([ 0.30948434, -0.38714003, -0.8291227 , -2.97435822, -0.98027682,
        1.1514002 , -0.55095555,  0.95711338,  0.19830638, -1.9949793 ,
        2.07008646,  1.40476188, -1.24604597,  1.11915287, -0.07821441,
        0.0085988 ,  0.67625228,  0.73340738,  0.10748256, -0.54564192,
        1.01053945,  0.21434811, -0.14660395, -1.67297697, -1.46236525,
        0.53303837,  0.45535831,  2.0715385 ,  1.22369479,  0.99701508,
        0.31653384, -0.1804105 ,  0.75835368, -0.82432677, -0.60901309,
       -1.00672324,  0.19796361,  0.23187855, -0.45089237,  0.99334206,
       -0.37360083, -1.56176183, -0.10603915, -0.83939339,  1.79691853,
       -1.30355765,  0.05389771, -0.58246293,  0.3189366 , -0.34234434,
       -0.00447535,  0.74915602, -0.231175  , -0.32885494, -2.28524844,
        0.79787151, -0.32812923,  0.34482507, -0.26954837,  0.73383739,
        0.13720868,  0.62233486,  0.28807992,  0.87892109, -0.0382785 ,
        1.42704137,  1.29214626, -1.85701151,  0.40088687,  0.27

In [88]:
np.random.randn(30,1)#-3 t0 +3 range

array([[ 1.78571824],
       [-0.05045602],
       [ 0.25376495],
       [-1.15129695],
       [-0.11700813],
       [-0.35452912],
       [ 0.48903368],
       [ 1.20862231],
       [-1.75184953],
       [ 0.99302202],
       [-0.95745458],
       [-1.74062775],
       [-0.65649844],
       [-0.79983575],
       [ 2.0833553 ],
       [-0.06635075],
       [-1.53218207],
       [-0.51249436],
       [-0.33103573],
       [-1.07179593],
       [-0.82009745],
       [-1.2194045 ],
       [-0.15676016],
       [ 0.49412298],
       [ 0.58329217],
       [ 0.0897187 ],
       [ 0.92076556],
       [-0.77434274],
       [-0.98812813],
       [ 0.78032923]])

In [90]:
np.random.normal(10,2,(4,5))

array([[11.07835249, 12.67028538,  8.82774228, 12.38967101,  8.05314821],
       [11.30618817,  9.94318983, 11.75516042, 11.9815079 , 10.11286717],
       [ 9.48506623, 12.83695317,  8.33832111,  6.66555506,  7.92427003],
       [ 6.3123932 , 10.77685949,  6.19931025,  7.91895132, 12.24666356]])

In [97]:
#to craete normal distribution
np.random.normal(40,5)

30.368809750594522

In [99]:
np.random.normal(40,5,(5,4))

array([[48.57843101, 34.23034367, 41.02153702, 33.05234083],
       [38.92498267, 36.0496549 , 37.19783337, 36.60019443],
       [36.2780414 , 33.28605134, 25.51600693, 48.0904736 ],
       [40.2691927 , 39.48114157, 43.98123806, 42.00492026],
       [26.25394384, 31.53604054, 37.81539293, 31.1077876 ]])

In [101]:
np.random.normal(10,2,(7,4))

array([[10.77030383, 12.85721503,  9.86236016,  7.90591986],
       [10.33076557,  7.47544894, 10.75758067,  8.43558523],
       [ 9.14583371, 13.81461162,  9.23205856,  8.98166444],
       [ 9.32030149, 11.56679902, 10.31635051, 13.06892151],
       [12.11080627, 11.02154773, 10.17590443,  9.69676424],
       [ 8.88202425, 10.67130248,  9.23677818, 10.9589183 ],
       [11.22597893, 11.47243413, 12.23872022, 12.40247353]])

In [105]:
np.random.randint(35,86)

37