In [2]:
import numpy as np

In [4]:
h=[30,20,5,8,9]
h

[30, 20, 5, 8, 9]

In [6]:
for i in range(len(h)):
    h[i] += 7
    

In [10]:
h

[37, 27, 12, 15, 16]

In [13]:
d=[]
for i in h:
    d.append(i+7)

In [15]:
d

[44, 34, 19, 22, 23]

In [21]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [23]:
list(s)

[6, 2, 3, 9, 7, 5, 8]

In [55]:
k=[]
for i in s:
    k.append(i**2)

In [57]:
k

[1296, 16, 81, 6561, 2401, 625, 4096]

In [35]:
tuple(k)

(36, 4, 9, 81, 49, 25, 64)

In [49]:
tuple(x**2 for x in s)

(36, 4, 9, 81, 49, 25, 64)

In [53]:
y=list(s)
k=[]
for i in y:
    k.append(i**2)
s=tuple(k)
s

(36, 4, 9, 81, 49, 25, 64)

In [71]:
l=[]
for i in s:
    if i>50:
        l.append(i)
l
    

[81, 64]

In [92]:
arr=np.array([20,50,30,70,80,40,36,54,23,98])

In [94]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [100]:
#we can directly apply operations on array
t=arr+7
t

array([ 27,  57,  37,  77,  87,  47,  43,  61,  30, 105])

In [102]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

In [110]:
k=arr*5
k

array([100, 250, 150, 350, 400, 200, 180, 270, 115, 490])

In [112]:
l=arr%4

In [114]:
l

array([0, 2, 2, 2, 0, 0, 0, 2, 3, 2], dtype=int32)

In [116]:
arr>50

array([False, False, False,  True,  True, False, False,  True, False,
        True])

In [118]:
arr[0]

20

In [120]:
arr[4:8]

array([80, 40, 36, 54])

In [122]:
arr[3:8:2]

array([70, 40, 54])

In [128]:
arr[3:6:1]

array([70, 80, 40])

In [154]:
#where function is used to index the elements satisfying condition
np.where(arr>50)

(array([3, 4, 7, 9], dtype=int64),)

In [130]:
#elements satisfying condition
arr[arr>50]

array([70, 80, 54, 98])

In [132]:
arr>=70

array([False, False, False,  True,  True, False, False, False, False,
        True])

In [136]:
arr[arr<=70]

array([20, 50, 30, 70, 40, 36, 54, 23])

In [138]:
k=[36,4,9,81,49,25,64]
k

[36, 4, 9, 81, 49, 25, 64]

In [152]:
index=[]
for i in range(len(k)):
    if k[i]>50:
        index.append(i)
index

[3, 6]