In [3]:
import numpy as np

In [4]:
a=np.random.randint(20,60,15)

In [6]:
a

array([30, 34, 48, 26, 23, 31, 59, 52, 52, 29, 24, 50, 49, 34, 47])

In [8]:
#negative index must be given for negative direction indexing
a[-5:-12:-1]

array([24, 29, 52, 52, 59, 31, 23])

In [5]:
np.random.seed(94)
b=np.random.randint(45,78,(7,8))

In [24]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [26]:
b.ndim

2

In [28]:
#to access any column we need to give :
b[:,4]

array([74, 69, 59, 65, 65, 60, 54])

In [30]:
b[:,7]#7th column

array([53, 60, 77, 55, 51, 47, 61])

In [32]:
b[1,3]#1st row 3rd column position

77

In [34]:
b[3,0]

46

In [36]:
b[2] #2nd row

array([71, 56, 51, 58, 59, 47, 68, 77])

In [38]:
b[5,6]

67

In [7]:
b[2]    

array([71, 56, 51, 58, 59, 47, 68, 77])

In [9]:
b[2,1:6]#left of comma is for rows and right of comma is for colums

array([56, 51, 58, 59, 47])

array[row-start : row-end : row-step]

In [11]:
b[1:6]

array([[61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47]])

In [13]:
b[1:6:2]

array([[61, 59, 55, 77, 69, 69, 48, 60],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [75, 67, 53, 77, 60, 67, 67, 47]])

In [15]:
b[1:6:2,1:6]

array([[59, 55, 77, 69, 69],
       [45, 52, 74, 65, 53],
       [67, 53, 77, 60, 67]])

In [19]:
b[3:6,2:6]

array([[52, 74, 65, 53],
       [46, 69, 65, 75],
       [53, 77, 60, 67]])

In [29]:
b[1:7:2,1:8:3]

array([[59, 69, 60],
       [45, 65, 55],
       [67, 60, 47]])